/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carta;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Carta
     */
    Baraja miBaraja = new Baraja();

    public Juego() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posicion1 = new javax.swing.JLabel();
        posicion2 = new javax.swing.JLabel();
        posicion3 = new javax.swing.JLabel();
        posicion4 = new javax.swing.JLabel();
        posicion5 = new javax.swing.JLabel();
        posicion6 = new javax.swing.JLabel();
        posicion7 = new javax.swing.JLabel();
        posicion8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());
        getContentPane().add(posicion1);
        getContentPane().add(posicion2);
        getContentPane().add(posicion3);
        getContentPane().add(posicion4);
        getContentPane().add(posicion5);
        getContentPane().add(posicion6);
        getContentPane().add(posicion7);
        getContentPane().add(posicion8);

        jMenu1.setText("Iniciar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Barajar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Repartir");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        miBaraja.crearMazo();
        JOptionPane.showMessageDialog(this, "Se ha creado el mazo");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        if (miBaraja.misCartas[0] instanceof Carta) {

            //1. Abrir el archivo
            File miArchivo = new File("baraja.jpg");
            //2. Extraer imagen a la memoria
            try {
                BufferedImage miImagen = ImageIO.read(miArchivo);

                int cartica = miBaraja.misCartas[1].posición;
                System.out.println(cartica);
                
                BufferedImage miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);

                //3. Asignar la image a la etiqueta
                ImageIcon miIcono = new ImageIcon(miniImagen);
                posicion1.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[0].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion2.setIcon(miIcono);
                
                //
                cartica = miBaraja.misCartas[2].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion3.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[3].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion4.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[4].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion5.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[5].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion6.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[6].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion7.setIcon(miIcono);
                //
                cartica = miBaraja.misCartas[7].posición;
                System.out.println(cartica);
                
                 miniImagen = miImagen.getSubimage(225 * (cartica % 13), 315 * (cartica / 13), 225, 315);
                 miIcono = new ImageIcon(miniImagen);
                posicion8.setIcon(miIcono);
                
                

                
             //   miEtiqueta.repaint();
             
            } catch (IOException ex) {
                System.out.println("La embarró!!!!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "No existe un mazo para repartir");
        }


    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

        if (miBaraja.misCartas[0] instanceof Carta) {
            miBaraja.barajar();
            JOptionPane.showMessageDialog(this, "El mazo ha sido barajado");
        } else {
            JOptionPane.showMessageDialog(this, "Para barajar debe existir un mazo");
        }


    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel posicion1;
    private javax.swing.JLabel posicion2;
    private javax.swing.JLabel posicion3;
    private javax.swing.JLabel posicion4;
    private javax.swing.JLabel posicion5;
    private javax.swing.JLabel posicion6;
    private javax.swing.JLabel posicion7;
    private javax.swing.JLabel posicion8;
    // End of variables declaration//GEN-END:variables
}
